name: CI/CD
on:
  workflow_dispatch:
  push:

jobs:
  style_checks:
    name: Run style checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        run: poetry install
      - name: Run style checks
        run: poetry run flake8 .
      - name: Run type checks
        run: poetry run mypy .
      - name: Run tests
        run: poetry run pytest --cov=app
